### ISSUE TITLE
any more detailed docs or examples?

### ISSUE THREAD

**Issue by beeplin** [feathersjs-ecosystem/feathers-permissions#5]
It seems that currently we don't have any completed docs/examples to show how the permission array and the three hooks works together.

**Comment by ekryski** [comment]
It's coming. I have a bunch locally. Just finalizing the API. Will be up in the next couple days.

**Comment by joshua1** [comment]
@ekryski I want to use this plugin but no info yet in the docs.

**Comment by rithvikvibhu** [comment]
Any progress on this?

**Comment by OmgImAlexis** [comment]
@ekryski any updates on this? It'd be nice to see some kind of public timeline.

**Comment by beeplin** [comment]
guys, just checkout the source code and it's not so hard to figure out how to use. It works amazingly~

**Comment by OmgImAlexis** [comment]
@beeplin with multiple branches of each different plugin it's not as easy as "just looking through the source code" and docs would help a LOT with new users of this project.

**Comment by MichaelErmer** [comment]
+1

**Comment by marcpaskell** [comment]
+1

**Comment by gorork** [comment]
@ekryski Any ETA on the "**one more breaking change and going out**" for those who feel less adventurous? :)

**Comment by MichaelErmer** [comment]
Check https://github.com/feathersjs/feathers-permissions/pull/25 its basically the same you just need `service: 'someSerivceName'` instead of `globalHook: true`.  

Add a `permissions` field of type that is an array to your user model and set it to `['*']`.

Run your app using `DEBUG=feathers-permissions:hooks:check-permissions npm start`so you see which permissions would enable the current request.

**Comment by ekryski** [comment]
@gorork no sorry. Been pretty busy with work and we found some limitations with the format `messages:*:[id]`. The problem is that doesn't really scale if you have a lot of records you need to have permissions on.

We need an `isOwner` hook and want to implement hooks and filters as described in this thread: https://github.com/feathersjs/feathers-permissions/issues/4. All of the common hooks like `some`, `when`, `every`, `unless` are all in. It's now a matter of polishing this up to respect that discussion, ensure it scales, and have `setPermissions` work as well.

I've had very limited time for open source stuff as of late. I have a bunch code written locally for this stuff but it's been a while since I looked at it and is still experimental.

If someone wants to take a crack at PRs then I'd be more than happy to review but I'll post an update on here when I've pushed up new code.

**Comment by daffl** [comment]
Closed via #34
