### ISSUE TITLE
How do we handle permissions in channels? 

### ISSUE THREAD

**Issue by kshitizshankar** [feathersjs-ecosystem/feathers-permissions#50]
I've been trying to find references that go over channels with respect to permissions and access control but haven't been able to find anything. 

What's the recommended way to handle permissions for sending out real time updates without it becoming a mess?

**Comment by daffl** [comment]
I'm not sure what you mean by mess but there is documentation on how to keep channels updated in https://docs.feathersjs.com/api/channels.html#keeping-channels-updated.

Since messages are only dispatched to a connection once, even if they are in multiple channels, one common way is to join a channel for every permission a user has.

```js
app.on('login', (payload, { connection }) => {
  if(connection && connection.user) {
    // Join the per-permission channel
    connection.user.permissions.forEach(name => app.channel(name).join(connection));
  }
});
```
