### ISSUE TITLE
"users:*:own" special permission

### ISSUE THREAD

**Issue by mcchrish** [feathersjs-ecosystem/feathers-permissions#7]
### Feature Request

Add a special permission somewhat like `"users:*:own"` where it add permission access level to the user's own information.

In creating a new users, usually, the `id` is auto generate by the database upon creation. So there's no easy way of knowing what the `id` would be before it will be populated in the database.
So `setPermissions` probably won't work as a `before` hook with an example:

```js
permissions.hooks.setPermissions({permissions: ['users:*:[id]'], field: 'permissions'})
```

An alternative would be is to have an after hook (when the `id` is already generated) that updates the permission. But that means there will be at least two `write` operations just to achieve the desired result.

With an `own` permission, this can be simply:
```js
permissions.hooks.setPermissions({permissions: ['users:*:own'], field: 'permissions'})
```

**Comment by ekryski** [comment]
Currently working on wrapping up the `setPermissions` hook which would will be more this syntax:

```js
permissions.hooks.setPermissions({permissions: ['users:*:[id]'], field: 'permissions'})
```

You are correct that it will be 2 writes but I think this is ok. Using the `id` style keeps it more flexible for other entities. So say a user can only edit or remove messages they have sent.

**Comment by ekryski** [comment]
This is currently up in PR #10 but I think needs to be refactored or split up into 2 hooks or go along with your suggestion. The current implementation, when used as an after hook, only supports updating the entity being acted on. For example, setting a users permissions after they are created. 

What we also want to support is updating a users permissions based on other objects they create. For example,

> A user creates a message. Either admins or them should be the only ones that can edit or remove that message.

Now, the way we are storing permissions makes this example kind of challenge to handle "ownership" because you could potentially create thousands of messages which would make your permissions array humongous and managing keeping it up to date if related entities are removed will be messy (if not impossible).

I was hoping to avoid pre-fetching the resources in order to check ownership but it's looking like that's not really possible....
